# Generated by Django 2.0.1 on 2018-01-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapu_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaShopBottomImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'dapu_shop_bottom_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DaShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dapu_shop_category',
                'managed': False,
            },
        ),
    ]
