# Generated by Django 2.0.1 on 2018-01-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapu_shop', '0002_dashopbottomimg_dashopcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dapushopshop',
            options={},
        ),
    ]
